version: "3"

services:
  frontend:
    image: webpack
    build:
      context: ./app
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules

volumes:
  node_modules: